Repository PurplePalette/sp-sub-audio, pull requests merged in 2022-09, with the labels that each got.

#14 ci(ci): change poetry link
  .github/workflows/ci.yml
Labels: bug

#13 build: update dependency 220911
  poetry.lock
Labels: enhancement

#15 docs(readme): add development setup
  README.md
Labels: documentation

#11 Fix: Correct English Grammar
  src/main.py
Labels: documentation
